stages:
  - test

test-oidc:
  stage: test
  tags:
    - sonarqubeprod

  id_tokens:
    AZURE_ID_TOKEN:
      aud: https://gitlab.anasource.com

  script:
    - echo "Testing GitLab OIDC..."
    - echo "Token length:"
    - echo -n "$AZURE_ID_TOKEN" | wc -c